name: Stack Testing CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y gcc valgrind cppcheck
    
    - name: Compile project
      run: |
        gcc -Wall -Wextra -std=c11 -g -o main main.c stack.c
        gcc -Wall -Wextra -std=c11 -g -o test_stack test_stack.c stack.c
    
    - name: Run unit tests
      run: ./test_stack
    
    - name: Memory leak check
      run: valgrind --leak-check=full --error-exitcode=1 ./test_stack
    
    - name: Static analysis
      run: cppcheck --enable=all --error-exitcode=1 stack.c main.c
